language: node_js
node_js:
  - 8
  - 10
cache:
  yarn: true
  directories:
    - node_modules
script:
  - npm run test:lint:js
  - npm run test:lint:css
  - npm test
  - yarn build
env:
  - CI=true
before_deploy:
  - npm install netlify-cli -g
deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN -p --dir ./build
  skip_cleanup: true
  on:
    branch: master
